"""
Django settings for divipay project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$%lng+s2t(j3(lk1plmvvabtu2y37q9)sq5r_ga#3tawwuwv(&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'card_control',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'divipay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'divipay.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter' : 'verbose'
        },
    },
    'loggers': {
        'card_control': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # <-- And here
    ],
}

CONTROL_MODEL_NAME_CHOICES = [
        ('MER_NAME', 'Merchant Name'),
        ('MER_CAT', 'Merchant Category'),
        ('MIN_AMT', 'Minimum Amount'),
        ('MAX_AMT', 'Maximum Amount'),
        ("COUNTRY", "Country Name")
]

CONTROL_DEFINITION = {
                "MER_NAME" : {
                        "type" : "String",
                        "input_validation" : {
                            "can_multiple_exists" : True,
                            "choices" : ["Woolworths", "Coles", "Twilio", "Subway", "Bunnings", "Facebook", "Officeworks", "AWS", "Zendesk"]
                        },
                        "src_comparison" : {
                            "variable_name" : "merchant",
                            "operator" : "IN"
                        }
                },
                "MER_CAT" : {
                        "type" : "String",
                        "input_validation" : {
                            "can_multiple_exists" : True,
                            "choices" : ["5411", "5734", "5814", "5251", "7311", "5943", "7399", "7372"],
                        },
                        "src_comparison" : {
                            "variable_name" : "merchant_category",
                            "operator" : "IN"
                        }
                        
                },
                "MIN_AMT" : {
                        "type" : "Integer",
                        "input_validation" : {
                            "min_value" : 0,
                            "max_value" : 100
                        },
                        "src_comparison" : {
                            "variable_name" : "amount",
                            "operator" : "GTE"
                        }
                },
                "MAX_AMT" : {
                        "type" : "Integer",
                        "input_validation" : {
                            "min_value" : 0,
                            "max_value" : 100
                        },
                        "src_comparison" : {
                            "variable_name" : "amount",
                            "operator" : "LTE"
                        }
                },
}

MANDATORY_CONTROLS = [
    "MAX_AMT", ["MER_NAME", "MER_CAT"]
    ]

from .settings_local import *

